### ISSUE TITLE
Error when installing from within Vscode

### ISSUE THREAD

**Issue by blaze-the-star** [dsobotta/godot-rust-vscode#1]
Attempting to install Godot Rust from within vscode produces the following error:
`"Can't install ''dsobotta.godot-rust-vscode" extension because it is not compatible with current version of VS Code (version 1.60.1). `

**Comment by dsobotta** [comment]
Can you provide more details on your environment? I've just updated the extension to work with Godot 4.0 beta 4 and the latest GDExtension sample project.

**Comment by blaze-the-star** [comment]
I tried installing it again and came across no errors. It seems you fixed it!

**Comment by dsobotta** [comment]
Glad to hear!
